name: Flubase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:

    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.1
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  date_field: ^3.0.5
  flutter_datetime_picker: ^1.5.1
  email_validator: '^2.1.16'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
