// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSWk44q4pFyGOlpAmarG1CLSRtRqtOXQ',
    appId: '1:240430843694:web:e92d642889d3b392519cbf',
    messagingSenderId: '240430843694',
    projectId: 'flutter-application-d5015',
    authDomain: 'flutter-application-d5015.firebaseapp.com',
    storageBucket: 'flutter-application-d5015.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGS1GTp4oZX1x1CrQPmt8JN7g7e2Ugmdk',
    appId: '1:240430843694:android:be73abf2e362101e519cbf',
    messagingSenderId: '240430843694',
    projectId: 'flutter-application-d5015',
    storageBucket: 'flutter-application-d5015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMUwKyGFNDopgcjv9SIDdNt0TAalVvCk',
    appId: '1:240430843694:ios:2e9abe5eb634e2a8519cbf',
    messagingSenderId: '240430843694',
    projectId: 'flutter-application-d5015',
    storageBucket: 'flutter-application-d5015.appspot.com',
    iosClientId: '240430843694-o8bjoi4neb7546t2qcsmg4cjqr7gu8k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMUwKyGFNDopgcjv9SIDdNt0TAalVvCk',
    appId: '1:240430843694:ios:3ec3a3f0b05c3ee8519cbf',
    messagingSenderId: '240430843694',
    projectId: 'flutter-application-d5015',
    storageBucket: 'flutter-application-d5015.appspot.com',
    iosClientId: '240430843694-78p4m5ali34ipqln90c1pu7hf5gvfrek.apps.googleusercontent.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
